app_name: api
webapps_dir: /vagrant
wsgi_file: wsgi.py
wsgi_callable: app
locale: en_US.UTF-8


postgresql:
  version: 9.3
  repo: 'deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'
  install_development_headers: true

  pg_username: vagrant
  pg_password: vagrant

  user: postgres
  group: postgres

  config:
    shared_buffers: 24MB
    work_mem: 1MB

    checkpoint_segments: 3
    checkpoint_completion_target: 0.5

    effective_cache_size: 128MB