---
# Util tasks

- name: updates a server
  apt: update_cache=yes

- name: upgrade a server
  apt: upgrade=full

- name: install utils
  action: apt pkg={{item}} state=installed
  become: true
  become_method: sudo
  with_items:
    - htop
    - tree

- name: add aliases to .bashrc
  action: lineinfile dest=/home/vagrant/.bashrc line="{{ item }}"
  with_items:
    - 'cd /vagrant'
    - 'alias flask="python3 /vagrant/manage.py"'