---
# Python tasks

- name: install common packages needed for python application development
  action: apt pkg={{item}} state=latest
  with_items:
    - libpq-dev
    - python3
    - python3-pip
    - python3-setuptools


- name: Install pip3 requirements
  become: true
  become_method: sudo
  pip:
    executable: pip3
    # extra_args: --upgrade
    requirements: /vagrant/requirements.txt